### PR TITLE
Exceptions are logged

### PR DESCRIPTION
**Pull request by nMustaki**

### CODE REVIEW

**Comment by marselester** [comment]
Thanks for contribution, I need to test the changes first.

**Comment by nMustaki** [comment]
Sure, I'll try to do it today

**Comment by marselester** [comment]
I have added exception logging based on your solution. Thank you!

**Comment by nMustaki** [comment]
I didn't knew about this formatException fonction, it's a good thing I
completly forgot (sorry...) to add some tests ;-)


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/


On Thu, Mar 2, 2017 at 9:39 AM, Marsel Mavletkulov <notifications@github.com

**Comment by marselester** [comment]
No worries :)

**Pull request closed without merging**
